# Netlify Build Configuration
[build]
  # Build command
  command = "npm run build"
  
  # Directory with the build output
  publish = "dist"
  
  # Functions directory (if needed in future)
  # functions = "netlify/functions"

# Redirects and rewrites — all routes redirect to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (example - add your own in Netlify dashboard)
# [build.environment]
#   VITE_GOOGLE_PLACES_API_KEY = "your-key-here"
#   VITE_GOOGLE_PLACE_ID = "your-place-id-here"
